### ISSUE TITLE
React Dev Tools

### ISSUE THREAD

**Issue by MDoughlin** [btholt/complete-intro-to-react-v8#60]
Hello, I am in on the React Dev Tools videos of this course and I have coded up to this point and I am getting an error.  The error I am getting is the "Uncaught ReferenceError: process is not defined" and google is telling me to fix it exactly how Brian is saying not to.  I have not come across a way to fix this and still having issues, has anyone else had this error and how did you fix it?  I do not have webpack installed or any of the ones Brian said in the video ... 
`Uncaught ReferenceError: process is not defined
    at node_modules/@babel/types/lib/definitions/core.js (core.ts:40:17)
    at __require (chunk-RSJERJUL.js?v=29b6a201:3:50)
    at node_modules/@babel/types/lib/definitions/index.js (index.ts:2:1)
    at __require (chunk-RSJERJUL.js?v=29b6a201:3:50)
    at node_modules/@babel/types/lib/validators/validate.js (validate.ts:1:1)
    at __require (chunk-RSJERJUL.js?v=29b6a201:3:50)
    at node_modules/@babel/types/lib/builders/validateNode.js (validateNode.ts:1:1)
    at __require (chunk-RSJERJUL.js?v=29b6a201:3:50)
    at node_modules/@babel/types/lib/builders/generated/index.js (index.ts:5:1)
    at __require (chunk-RSJERJUL.js?v=29b6a201:3:50)`

**Comment by dtauer** [comment]
Were you still having issues? I tested the project (using Node version 16) and it worked. Brian doesn't use Webpack in the course so you shouldn't need that. The two things I would try:
- Make sure you are using Node version 16 or higher
- Try pulling down the code from the next checkpoint (after the React Router lesson) and start fresh from there: https://github.com/btholt/citr-v8-project/tree/main/08-react-router
